# MCU settings
MCU_SERIES = h7
MCU_ARCH = stm32
CMSIS_MCU = STM32H750xx
MICROPY_FLOAT_IMPL = single
AF_FILE = boards/stm32h743_af.csv
LD_FILES = $(BOARD_DIR)/h750-2mbflash.ld boards/common_blifs.ld
TEXT0_ADDR = 0x08040000

# MicroPython settings
MICROPY_PY_BLUETOOTH = 0
MICROPY_BLUETOOTH_NIMBLE = 0
MICROPY_BLUETOOTH_BTSTACK = 0
MICROPY_PY_LWIP = 0
MICROPY_PY_NETWORK_CYW43 = 0
MICROPY_PY_USSL = 0
MICROPY_SSL_MBEDTLS = 0
MICROPY_VFS_LFS2 = 1

FROZEN_MANIFEST = $(BOARD_DIR)/manifest.py

# black magic probe
MODULE_BMP_ENABLED=1
BMP_ADD_MISSING=1
MODULE_FREEDAP_ENABLED=1

#not truncated
